version: '3.8'

services:
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    depends_on:
            - redis
  redis:
        image: redis:6.2-alpine
        restart: "always"
        ports:
          - "6379:6379"
        volumes:
          - ../data/redis:/data
        entrypoint: redis-server --appendonly yes
